# Generated by Django 4.2.6 on 2023-11-04 01:09

import apps.compras.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.CharField(default=apps.compras.models.conver_encode, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=155, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(default=apps.compras.models.conver_encode, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('cod_producto', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Código de producto')),
                ('nombre', models.CharField(max_length=155, verbose_name='Nombre')),
                ('detalle', models.TextField(blank=True, max_length=555, null=True, verbose_name='Detalle')),
                ('costo', models.FloatField(blank=True, default=0, null=True, verbose_name='Costo')),
                ('stock', models.IntegerField(blank=True, default=0, null=True, verbose_name='Stock')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorias', models.ManyToManyField(to='compras.categoria', verbose_name='Categorias')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.CharField(default=apps.compras.models.conver_encode, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('costo', models.FloatField(default=0, verbose_name='Costo')),
                ('total_compra', models.FloatField(default=0, editable=False, verbose_name='Total de la compra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='compras.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compra',
            },
        ),
    ]
