# Generated by Django 4.2.6 on 2023-11-04 01:09

import apps.ventas.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(default=apps.ventas.models.conver_encode, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=155, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=155, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=155, verbose_name='Apellido Materno')),
                ('telefono', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefono')),
                ('zona', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zona')),
                ('av_calle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Avenida/Calle')),
                ('numero', models.IntegerField(blank=True, default=0, null=True, verbose_name='Número')),
                ('genero', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=125, verbose_name='Género')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.CharField(default=apps.ventas.models.conver_encode, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('cod_venta', models.CharField(default=apps.ventas.models.conver_encode, editable=False, max_length=100, unique=True)),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('total_venta', models.FloatField(default=0, editable=False, verbose_name='Total de venta')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de venta')),
                ('estado', models.CharField(choices=[('Venta', 'Venta'), ('Pedido', 'Pedido')], default='Venta', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='compras.categoria', verbose_name='Categoria')),
                ('cliente', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='ventas.cliente', verbose_name='Cliente')),
                ('producto', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='compras.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
            },
        ),
    ]
